org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.08.20-1.20.1
mod_id=tlm_companionship
mod_name=车万女仆：朝夕相伴
mod_name_en=Touhou Little Maid: Companionship
mod_license=MIT
mod_version=0.0.1
mod_group_id=com.laixia.maidintelligence
mod_authors=铼夏
mod_description=为 TLM 添加成长、饥饿状态、智能工作模式、自定义 AI 行为与更多互动。
